import type { NextPage } from "next";
import Head from "next/head";
import LoginForm from "../components/auth/LoginForm";

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginForm />
      </div>
    </main>
  );
};

export default Home;
